story4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from story4_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home , name='home'),
    path('resume/',views.resume , name='resume'),
    path('story1/',views.story1 , name='story1'),
    path('story5/add',views.story5_add, name='story5_add'),
    path('story5/',views.story5, name='story5'),
    path('story5/<int:my_id>/', views.story5_detail, name='story5_detail'),
    path('story5/<int:my_id>/delete', views.delete_view, name='matkul_delete'),
    path('story6/',include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story_8.urls')),
    path('story9/', include('story_9.urls')),
]

story6/urls.py
from django.urls import path
from .views import add, display, add_events
#url for app
urlpatterns = [
    path('', display, name='main_page'),
    path('add/', add, name='add_people'),
    path('add_events/', add_events, name='add_event')
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.home, name='FAQ'),
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.home, name='search'),
    path('<str:title>/', views.search_book),
]

story_9/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import register

app_name = 'story_9'

urlpatterns = [
    # path('register/', views.register, name='register'),
    path('login/', av.LoginView.as_view(template_name='auth.html'), name='auth'),
    path('logout/', av.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register, name='register'),
]

story4_app/models.py
from django.db import models

class Matkul(models.Model) :
    title = models.CharField(max_length=100)
    description = models.TextField()
    dosen = models.CharField(max_length=100)
    sks = models.PositiveSmallIntegerField()
    semester = models.PositiveIntegerField()
    room = models.CharField(max_length=10)

    def __str__(self): 
        return self.title

    #Title (str), Description (str), dosen (str), sks (int), smester tahun (int), ruang kelas (str)
# Create your models here.

story6/models.py
from django.db import models

class Events(models.Model) :
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

class People(models.Model):
    full_name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=20)
    events_registered = models.ForeignKey(Events, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name

story7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.

story4_app/forms.py
from django import forms

from .models import Matkul

class ProductForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'title',
            'description',
            'dosen',
            'sks',
            'semester',
            'room'
        ]

story6/forms.py
from django.db.models import fields
from django import forms
from django.forms import ModelForm, Textarea, TextInput
from django.forms import widgets
from .models import People, Events

# Form Class
class PeopleForm(ModelForm):
    class Meta:
        model = People
        fields = ['full_name','nickname','events_registered']
        widgets = {
            'full_name': TextInput(attrs={'placeholder': 'ex: Rengoku Kyojuro', 'required': True}),
            'nickname': TextInput(attrs={'placeholder': 'ex: Kyojuro', 'required': True}),
            }

class EventsForm(ModelForm):
    class Meta:
        model = Events
        fields = ['title']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'ex: Riding Trains', 'required': True}),
        }

story_9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1','password2']

story4_app/views.py
from django.shortcuts import render, redirect

from django.shortcuts import get_object_or_404, render, HttpResponseRedirect 

from .forms import ProductForm

from .models import Matkul

# Create your views here.
def home(request):
    return render(request,'main.html')

def resume(request):
    return render(request,'index2.html')

def story1(request):
    return render(request,'index.html')

def story5(request):
    obj = Matkul.objects.all()
    context = {
        'object': obj
    }
    return render(request, "matkul_list.html", context)

def story5_add(request):
    form = ProductForm(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('home')

    context = {
        'form': form
    }
    return render(request, "matkul_create.html", context)

def story5_detail(request, my_id):
    obj = Matkul.objects.get(id=my_id)
    context = {
        'object':obj
    }
    return render(request, "matkul_detail.html", context)

def delete_view(request, my_id): 
    obj = Matkul.objects.get(id=my_id)
    obj.delete()  
    return redirect ('story5') 

story6/views.py
from django.shortcuts import redirect,render
from django.http import request
from .models import Events, People
from .forms import EventsForm, PeopleForm

# Create your views here.

def add(request):
    form = PeopleForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('main_page')
    context = {'page_title':'Register','form':form}
    return render(request, 'add_people.html', context)

def display(request):
    people = People.objects.all()
    events = Events.objects.all()
    context = {'people': people, 'events': events, 'page_title' : "Events"}
    return render(request, "main_page.html",context)

def add_events(request):
    form = EventsForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('main_page')
    context = {'page_title': 'Register', 'form':form}
    return render(request, 'add_event.html', context)

story7/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'FAQ.html')

story_8/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
import urllib.request, json


# Create your views here.
def home(request):
    return render(request, 'search.html')

def search_book(request,title):
    link = urllib.parse.quote("https://www.googleapis.com/books/v1/volumes?q="+title,"/:?=")
    with urllib.request.urlopen(link) as url:
        global data
        data = json.loads(url.read().decode())
    return JsonResponse(data)

story_9/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}!')
            return redirect('story_9:auth')
    else:
        form = RegisterForm()
    context = {'form':form}
    return render(request,'register.html',{'form':form})

# def home(request):
#     return render(request, 'auth.html')

story4_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
        <title>Story 3</title>
    </head>
<body>
    <!-- <nav class="navbar navbar-light" style="background-color: #F4DCDC;width: 100%; justify-content: center;">
        <a href="#" class="navbar-brand" style="color:#FFFFFF;font-weight: 900;font-family: nunito sans;">CURRICULUM VITAE</a>
        <div class="options" style="background-color: black;"></div>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F4DCDC;">
        <a class="navbar-brand" href="#">Hello Web !</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Story
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'story1' %}">Story 1</a>
                <a class="dropdown-item" href="https://www.figma.com/file/O0vbFzvGTSIuMt2ZprhWzA/Story-2">Story 2</a>
                <a class="dropdown-item" href="{% url 'story5' %}">Story 5</a>
                <a class="dropdown-item" href="{% url 'main_page' %}">Story 6</a>
                <a class="dropdown-item" href="{% url 'story7:FAQ' %}">Story 7</a>
                <a class="dropdown-item" href="{% url 'story_8:search' %}">Story 8</a>
                <a class="dropdown-item" href="{% url 'story_9:auth' %}">Story 9</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">...</a>
              </div>
            </li>
          </ul>
            <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"> Hello, {{ user.username }} </a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'story_9:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'story_9:auth' %}">Login</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'story_9:register' %}"> Register</a>
                        </li>
                    {% endif %}
                    </ul>  
        </div>
      </nav>
    
    
    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
</body>
</html>

story4_app/templates/main.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
</head>
<body style="background-image: url(https://files.catbox.moe/qai26i.svg);background-position: center;background-repeat: no-repeat;background-size: cover; background-color: #FFE3B8;"> -->


{% extends 'base.html' %}
{% load static %}

{% block content %}
    <p style="font-size: 5rem; font-weight: 900; text-align: center; padding-top: 3%;" >Welcome To My Web</p>
    <br>
    <p style="font-size: 3rem;font-weight: 300; text-align: center; color: #FFE3B8; padding-top: 3%;">“Today i choose joy” -Kevin Aucoin</p>
    <div class="contain_fluid" style="padding-bottom: 10%;">
        <div class="rowx">
            <div class="colx">
                <a href="{% url 'resume' %}">
                    <img src="https://files.catbox.moe/g0v4em.svg" alt="This text is shown if server fails to load image" />
                </a>
            </div>
            <div class="colx">
                 <img src="https://files.catbox.moe/hrr6kx.svg" alt="This text is shown if server fails to load image" />
            </div>
            <div class="colx">
                <img src="https://files.catbox.moe/maw3fj.svg" alt="">
            </div>
        </div>
    </div>

    <div class="contain_fluid" style="position: fixed; height: auto;bottom: 0; width: 100%;">
        <div class="rowx" style="background-color: #F4DCDC;padding-top:0; padding-bottom: 0; height: auto; width: 100%; padding-right: 0; margin-right: 0;margin-left:0;">
            <div class="colx" style="padding-top: 0;">
                <a href="#" class="navbar-brand" style="color:#FFFFFF;font-weight: 900;font-family: nunito sans; ">CONTACT ME HERE!</a>
            </div>
            <div class="colx" style="padding-top: 0;">
              <img src="https://files.catbox.moe/18u7oo.png" />
            </div>
            <div class="colx" style="padding-top: 0;">
                <img src="https://files.catbox.moe/oi5m49.png" alt="">
            </div>
            <div class="colx" style="padding-top: 0;">
                <img src="https://files.catbox.moe/gpcg4m.png" alt="">
            </div>
            <div class="colx" style="padding-top: 0;">
                <img src="https://files.catbox.moe/3yll1h.png" alt="">
            </div>
            <div class="colx" style="padding-top: 0;">
                <img src="https://files.catbox.moe/a0kywt.png" alt="">
            </div>
            <div class="colx" style="padding-top: 0;">
                <img src="https://files.catbox.moe/1jlwlq.png" alt="">
            </div>
        </div>
    </div>

{% endblock %}

story4_app/templates/matkul_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container" style="padding-top: 2%;">
    <h1 class="col-xl-12 col-lg-12 col-md-12 col-sm-12"> Create new Matkul </h1>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 center"></div>
        <form method = "POST" >
            {% csrf_token %}
            
            {{ form|crispy }}
            <input type="submit" value="Save"> 
        </form>
    </div>
</div>
{% endblock %}

story4_app/templates/matkul_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <br>
    <h3>Detail Mata Kuliah</h3>
    <br>
    <div class="table-responsive">
        <table class="table">
            <tbody>
                <tr>
                  <th scope="row">Mata Kuliah</th>
                  <td>{{object.title}}</td>
                </tr>
                <tr>
                  <th scope="row">Jumlah SKS</th>
                  <td>{{object.sks}}</td>  
                </tr>
                <tr>
                  <th scope="row">Semester</th>
                  <td>{{object.semester}}</td>
                </tr>
                <tr>
                    <th scope="row">Dosen Pengajar</th>
                    <td>{{object.dosen}}</td>
                </tr>
                <tr>
                    <th scope="row">Room</th>
                    <td>{{object.room}}</td>
                  </tr>
                  <tr>
                      <th scope="row">Description</th>
                      <td>{{object.description}}</td>
                  </tr>
              </tbody>
        </table>
        
      </div>

{% endblock %}

story6/templates/add_event.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block content  %}
    <br>
    <h1 class="col-xl-12 col-lg-12 col-md-12 col-sm-12"> Add </h1>
        <br>
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 center">
            <form method = "POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-light" type="submit" value="Submit">
            </form>
        </div>
    {% endblock  %}

story7/templates/basefaq.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/stylex.css' %}">
        <title>Story 3</title>
    </head>
<body>
    <!-- <nav class="navbar navbar-light" style="background-color: #F4DCDC;width: 100%; justify-content: center;">
        <a href="#" class="navbar-brand" style="color:#FFFFFF;font-weight: 900;font-family: nunito sans;">CURRICULUM VITAE</a>
        <div class="options" style="background-color: black;"></div>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F4DCDC;">
        <a class="navbar-brand" href="#">Hello Web !</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Story
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'story1' %}">Story 1</a>
                <a class="dropdown-item" href="https://www.figma.com/file/O0vbFzvGTSIuMt2ZprhWzA/Story-2">Story 2</a>
                <a class="dropdown-item" href="{% url 'story5' %}">Story 5</a>
                <a class="dropdown-item" href="{% url 'main_page' %}">Story 6</a>
                <a class="dropdown-item" href="{% url 'story7:FAQ' %}">Story 7</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">...</a>
              </div>
            </li>
        </div>
      </nav>
    
    
    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
</body>
</html>

story_8/templates/basesearch.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/stylex.css' %}">
        <title>Story 3</title>
    </head>
<body>
    <!-- <nav class="navbar navbar-light" style="background-color: #F4DCDC;width: 100%; justify-content: center;">
        <a href="#" class="navbar-brand" style="color:#FFFFFF;font-weight: 900;font-family: nunito sans;">CURRICULUM VITAE</a>
        <div class="options" style="background-color: black;"></div>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F4DCDC;">
        <a class="navbar-brand" href="#">Hello Web !</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Story
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'story1' %}">Story 1</a>
                <a class="dropdown-item" href="https://www.figma.com/file/O0vbFzvGTSIuMt2ZprhWzA/Story-2">Story 2</a>
                <a class="dropdown-item" href="{% url 'story5' %}">Story 5</a>
                <a class="dropdown-item" href="{% url 'main_page' %}">Story 6</a>
                <a class="dropdown-item" href="{% url 'story7:FAQ' %}">Story 7</a>
                <a class="dropdown-item" href="{% url 'story_8:search' %}">Story 8</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">...</a>
              </div>
            </li>
        </div>
      </nav>
    
    
    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
{% block extra_script %}
{% endblock %}
</body>
</html>

story_9/templates/baseauth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/stylex.css' %}">
        <title>Story 3</title>
    </head>
<body>
    <!-- <nav class="navbar navbar-light" style="background-color: #F4DCDC;width: 100%; justify-content: center;">
        <a href="#" class="navbar-brand" style="color:#FFFFFF;font-weight: 900;font-family: nunito sans;">CURRICULUM VITAE</a>
        <div class="options" style="background-color: black;"></div>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F4DCDC;">
        <a class="navbar-brand" href="#">Hello Web !</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Story
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'story1' %}">Story 1</a>
                <a class="dropdown-item" href="https://www.figma.com/file/O0vbFzvGTSIuMt2ZprhWzA/Story-2">Story 2</a>
                <a class="dropdown-item" href="{% url 'story5' %}">Story 5</a>
                <a class="dropdown-item" href="{% url 'main_page' %}">Story 6</a>
                <a class="dropdown-item" href="{% url 'story7:FAQ' %}">Story 7</a>
                <a class="dropdown-item" href="{% url 'story_8:search' %}">Story 8</a>
                <a class="dropdown-item" href="{% url 'story_9:auth' %}">Story 9</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">...</a>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link"> Hello, {{ user.username }} </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'story_9:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_9:auth' %}">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'story_9:register' %}"> Register</a>
                </li>
            {% endif %}
            </ul>  
        </div>
      </nav>
    
    
    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
{% block extra_script %}
{% endblock %}
</body>
</html>